config/routes.rb
Rails.application.routes.draw do

  scope '/:locale' do
    mount Forem::Engine, :at => '/forums'

    devise_for :users

    get 'students'                    => 'students#index'
    post 'students/filter'                   => 'students#filter', as: 'filter_student'

    get 'group/index'                       => 'group#index'
    get 'users_list'                        => 'uuser#index'
    get 'users_list/:id'                    => 'uuser#show'
    get 'users_list/:id/logas'              => 'uuser#become_user', as: "admin_logas_user"
    get 'users_list/change_locale/:locale'  => 'uuser#set_local', as: "change_locale_user"

    get 'welcomes'                          => 'welcomes#index'
    get 'sujet/framework0'                  => 'welcomes#framework0'
    get 'sujet/framework1'                  => 'welcomes#framework1'
    get 'sujet/framework2'                  => 'welcomes#framework2'
    get 'sujet/bigwebproject'               => 'welcomes#bigwebproject'

    get 'contact'                           => 'contact#index'
    get 'contact/new'                       => 'contact#new'
    post 'contact/create'                   => 'contact#create'
    get 'contact/:id'                       => 'contact#show'

    get 'log/index'

    resources :tickets do
      resources :comments
    end

    get '/user/tickets'                     => 'tickets#user_index'

    scope '/adm' do
      get '/ticket/:id'                     => 'tickets#show_admin', as: "adm_ticket_show"
      get '/ticket/:id/edit'                => 'tickets#edit_admin', as: "adm_ticket_edit"
      patch '/ticket/:id/edit'              => 'tickets#update_admin'
    end

  end

  ActiveAdmin.routes(self)
  root :to => 'welcomes#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessor :login
  attr_accessor :cn
  attr_accessor :uidnumber


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :logg, only: [:index, :filter]

  def index
    ap "index"
    ldap = Net::LDAP.new(
      :host => 'ldap.42.fr',
      :port => 636,
      :encryption => :simple_tls,
      :method => :simple
    )

    @entries = ldap.search(
      :base => 'ou=august,ou=2013,ou=paris,ou=people,dc=42,dc=fr',
      :filter => Net::LDAP::Filter.eq( "uid", "*" ),
      :attributes => [ 'uidNumber', 'uid', 'cn', 'givenName', 'sn']
    )

    if params.has_key?(:uidNumber)
      @entries = @entries.sort_by { |entry| entry.uidNumber } if params[:uidNumber] == "ASC"
      @entries = @entries.sort_by { |entry| entry.uidNumber }.reverse if params[:uidNumber] == "DESC"
    elsif params.has_key?(:uid)
      @entries = @entries.sort_by { |entry| entry.uid } if params[:uid] == "ASC"
      @entries = @entries.sort_by { |entry| entry.uid }.reverse if params[:uid] == "DESC"
    elsif params.has_key?(:cn)
      @entries = @entries.sort_by { |entry| entry.cn } if params[:cn] == "ASC"
      @entries = @entries.sort_by { |entry| entry.cn }.reverse if params[:cn] == "DESC"
    elsif params.has_key?(:givenName)
      @entries = @entries.sort_by { |entry| entry.givenName } if params[:givenName] == "ASC"
      @entries = @entries.sort_by { |entry| entry.givenName }.reverse if params[:givenName] == "DESC"
    elsif params.has_key?(:sn)
      @entries = @entries.sort_by { |entry| entry.sn } if params[:sn] == "ASC"
      @entries = @entries.sort_by { |entry| entry.sn }.reverse if params[:sn] == "DESC"
    end

    @student = Student.new

  end

  def filter

    ap "Filter"
    ldap = Net::LDAP.new(
      :host => 'ldap.42.fr',
      :port => 636,
      :encryption => :simple_tls,
      :method => :simple
    )
    f_params = filter_params

    ap params
    if f_params.has_key?(:login)
      fil_login = Net::LDAP::Filter.eq( "uid", "#{f_params[:login].to_s}*" )
    end
    if f_params.has_key?(:cn)
      fil_cn = Net::LDAP::Filter.eq( "cn", "#{f_params[:cn].to_s}*" )
    end
    if f_params.has_key?(:uidnumber)
      fil_uidnumber = Net::LDAP::Filter.eq( "uid", "#{f_params[:uidnumber].to_s}*" )
    end

    if fil_login && fil_cn && fil_uidnumber
      fil_1 = Net::LDAP::Filter.join(fil_login, fil_cn)
      fil_2 = Net::LDAP::Filter.join(fil_1, fil_uidnumber)
      fil_1 = fil_2
    elsif fil_login && fil_cn
      fil_1 = Net::LDAP::Filter.join(fil_login, fil_cn)
    elsif fil_login && fil_uidnumber
      fil_1 = Net::LDAP::Filter.join(fil_login, fil_uidnumber)
    elsif fil_cn && fil_uidnumber
      fil_1 = Net::LDAP::Filter.join(fil_cn, fil_uidnumber)
    end

    if fil_1
      ftth = fil_1
    elsif fil_login
      ap "Filter 1"
      ftth = fil_login
    elsif fil_cn
      ftth = fil_cn
    elsif fil_uidnumber
      ftth = fil_uidnumber
    else
      ftth = Net::LDAP::Filter.eq( "uid", "*" )
    end

    @entries = ldap.search(
      :base => 'ou=august,ou=2013,ou=paris,ou=people,dc=42,dc=fr',
      :filter => ftth,
      :attributes => [ 'uidNumber', 'uid', 'cn', 'givenName', 'sn']
    )
    if f_params
      @student = Student.new(
        login: f_params[:login],
        cn: f_params[:cn],
        uidNumber: f_params[:uidnumber]
      )
      ap @student
    else
      @student = Student.new
    end

  end

  private
  def filter_params
    params.require(:student).permit(:login, :cn, :uidnumber)
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_filter.html.slim
.row
  .col-sm-12
    = simple_form_for @student, :url => filter_student_url do |f|

      .col-sm-4
        = f.input :login

      .col-sm-5
        = f.input :cn

      .col-sm-3
        = f.input :uidnumber

      .col-sm-2
        = f.submit t('student.filter'), :class => "btn btn-info"

      .col-sm-2
        = link_to t('student.reset'), students_path, :class => "btn btn-info"

app/views/students/_list.html.slim
- if @entries
  table.table.table-striped
    tr
      td
        b uidNumber
        - if params[:action] == "index"
          | &nbsp;&nbsp;
          = link_to "ASC", students_url( :uidNumber => "ASC" )
          | &nbsp;&nbsp;
          = link_to "DESC", students_url( :uidNumber => "DESC" )
      td
        b uid
        - if params[:action] == "index"
          | &nbsp;&nbsp;
          = link_to "ASC", students_url( :uid => "ASC" )
          | &nbsp;&nbsp;
          = link_to "DESC", students_url( :uid => "DESC" )
      td
        b cn
        - if params[:action] == "index"
          | &nbsp;&nbsp;
          = link_to "ASC", students_url( :cn => "ASC" )
          | &nbsp;&nbsp;
          = link_to "DESC", students_url( :cn => "DESC" )
      td
        b givenName
        - if params[:action] == "index"
          | &nbsp;&nbsp;
          = link_to "ASC", students_url( :givenName => "ASC" )
          | &nbsp;&nbsp;
          = link_to "DESC", students_url( :givenName => "DESC" )
      td
        b sn
        - if params[:action] == "index"
          | &nbsp;&nbsp;
          = link_to "ASC", students_url( :sn => "ASC" )
          | &nbsp;&nbsp;
          = link_to "DESC", students_url( :sn => "DESC" )
    - @entries.each do |f|
      tr
        td = f.uidNumber.to_s.sub!('["', "").sub!('"]', "")
        td = f.uid.to_s.sub!('["', "").sub!('"]', "")
        td = f.cn.to_s.sub!('["', "").sub!('"]', "")
        td = f.givenName.to_s.sub!('["', "").sub!('"]', "")
        td = f.sn.to_s.sub!('["', "").sub!('"]', "")

app/views/students/filter.html.slim
h1 Students#Filter
p Find me in app/views/students/index.html.slim

.row
  = render 'students/filter'

br
br
.row
  = render 'list'

app/views/students/index.html.slim
h1 Students#index
p Find me in app/views/students/index.html.slim

.row
  = render 'students/filter'

br
br
.row
  = render 'list'