config/routes.rb
Rails.application.routes.draw do

  scope '/:locale' do
    mount Forem::Engine, :at => '/forums'

    devise_for :users

    get 'students'                    => 'students#index'
    post 'students/filter'                   => 'students#filter', as: 'filter_student'

    get 'group/index'                       => 'group#index'
    get 'users_list'                        => 'uuser#index'
    get 'users_list/:id'                    => 'uuser#show'
    get 'users_list/:id/logas'              => 'uuser#become_user', as: "admin_logas_user"
    get 'users_list/change_locale/:locale'  => 'uuser#set_local', as: "change_locale_user"

    get 'welcomes'                          => 'welcomes#index'
    get 'sujet/framework0'                  => 'welcomes#framework0'
    get 'sujet/framework1'                  => 'welcomes#framework1'
    get 'sujet/framework2'                  => 'welcomes#framework2'
    get 'sujet/bigwebproject'               => 'welcomes#bigwebproject'

    get 'contact'                           => 'contact#index'
    get 'contact/new'                       => 'contact#new'
    post 'contact/create'                   => 'contact#create'
    get 'contact/:id'                       => 'contact#show'

    get 'log/index'

    resources :tickets do
      resources :comments
    end

    get '/user/tickets'                     => 'tickets#user_index'

    scope '/adm' do
      get '/ticket/:id'                     => 'tickets#show_admin', as: "adm_ticket_show"
      get '/ticket/:id/edit'                => 'tickets#edit_admin', as: "adm_ticket_edit"
      patch '/ticket/:id/edit'              => 'tickets#update_admin'
    end

  end

  ActiveAdmin.routes(self)
  root :to => 'welcomes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates_presence_of :title
  validates_presence_of :message
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
  def login
    if !self.user_id.blank?
      User.find(self.user_id).login
    else
      "No User Id"
    end
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessor :login
  attr_accessor :cn
  attr_accessor :uidnumber


end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true
  validates :message, presence: true

  ### User
  def self.user_ticket_open_all(userId)
    self.where(user_id: userId, open: true)
  end

  def self.user_ticket_close_all(userId)
    self.where(user_id: userId, open: false)
  end

  ### Admin
  def self.ticket_open_all
    self.where(open: true)
  end

  def self.ticket_close_all
    self.where(open: false)
  end

  def self.ticket_no_assign
    self.where(open: true, admin_assign_id: nil)
  end

  def self.ticket_assign_to_me(userId)
    self.where(admin_assign_id: userId, open: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => {email: false, login42: true}

  validates :login, presence: true, uniqueness: true

   attr_accessor :login42

  # hack for remember_token
  def authenticatable_token
    Digest::SHA1.hexdigest(email)[0,29]
  end

  # Front-end navbar administration button
  def admin?
    if self && self.admin
      true
    else
      false
    end
  end

  def current_admin
    self && self.admin == true
  end

  def current_admin_forum
    self && self.forem_admin == true
  end

  # Forem
  def forem_name
    self.login
  end

  # Forem email gravatar
  def forem_email
    self.email
  end

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_action :logg, only: [:show, :create, :index, :destroy]
  def index
    @contacts = Contact.all
  end

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path
    else
      @contact_error = "Create Failed"
    end
  end

  def show
  end

  def contact_params
    params.require(:contact).permit(:firstname, :lastname, :entity, :phone, :email, :title, :message)
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!
  before_action :logg, only: [:index]

  def index
    @groups = Group.all
  end
end

app/controllers/log_controller.rb
class LogController < ApplicationController
  before_action :authenticate_user!
  before_action :logg, only: [:index, :destroy]

  def index
    @logs = Log.all.limit(20).order('created_at DESC')
  end

  def destroy
  end
end

app/controllers/page_controller.rb
class PagesController < ApplicationController
  #before_action :authenticate_user!
  before_action :logg, only: [:index]


  def index
  end

end

app/controllers/uuser_controller.rb
class UuserController < ApplicationController
  before_action :authenticate_admin!

  before_action :logg, only: [:index, :show]

  def index
    @users = User.all
  end

  def show
  end

  def become_user
    return unless authenticate_admin!
    sign_in(:user, User.find(params[:id]), { :bypass => true })
    redirect_to root_url
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :logg, only: [:index, :show, :framework0, :framework1, :framework2, :bigwebproject]

  def index
    # passwd = jmoiroux_passwd
    # user = "jmoiroux"
    # ldap = Net::LDAP.new(
    #   :host => 'ldap.42.fr',
    #   :port => 636,
    #   :encryption => :simple_tls
    # )
    #
    # @result = ldap.bind_as(
    #   :base => 'dc=42,dc=fr',
    #   :filter => "(uid=#{user})",
    #   :password => passwd
    # )
  end

  def filter
  end

  def framework0
  end

  def framework1
  end

  def framework2
  end

  def bigwebproject
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def resource_name
    :ticket
  end

  def resource_class
    Ticket
  end

  def resource
    @ticket ||= Ticket.new
  end

  def comment_resource_name
    :comment
  end

  def comment_resource_class
    Comment
  end

  def comment_resource
    @comment ||= Comment.new
  end

end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/bigwebproject.html.slim
h1 Sujet Big Project Web

app/views/welcomes/framework0.html.slim
.container
  h1 Sujet Framework 0

  h2 Chapitre II

  h3 Sujet
  h4 II.1
  h5 Installation et Configuration

  p
    | Suite à la piscine PHP, vous allez maintenant pratiquer la mise en place et l’utilisation
    | d’un framework. Vous aller avoir deux projets qui suivent et qui vont utiliser cette base
    | que vous aurez préparé. Pour ceux qui ne savent pas ce qu’est un framework, vous pouvez
    | consulter cette page web : ici.

  p
    | Pour cette première étape, nous vous demandons d’installer et de configurer correc-
    | tement les éléments suivants :

  p
    | • Un serveur web : Vous devez installer un server web (au choix Apache, Nginx ou
    | Lighthttpd). Celui-ci doit avoir au minimum un VirtualHost. Il devra être capable
    | d’interpréter le code de votre site, peut importe le langage. À vous d’installer les
    | modules appropriés.

  p
    | • Un framework : Pour le choix du framework vous êtes libre d’utiliser celui que
    | vous voulez tant qu’il respecte le modèle MVC (Modèle, Vue, Controlleur) et vous
    | pouvez choisir le langage de votre choix.

  p
    | • Une base de données : Vous devez choisir la base de données la plus adapté à
    | votre langage/framework. Celle-ci devra être relié via les fichiers de configurations
    | proposés par le framework choisi.

  p
    | Vous devez rendre dans votre dépot uniquement le dossier du framework. Un ‘git
    | clone‘ dans un dossier pointé par votre virtual host devra rendre votre site fonctionnel.
    | La soutenance se fera donc sur votre poste, avec votre base de données et votre serveur
    | web pré-configuré. Vous n’aurez en revanche, pas le droit de toucher au code de votre
    | framework une fois l’heure du rendu atteinte.

  p
    | Cette partie est obligatoire et ne compte que pour la moitié de votre note.

  br
  br
  h4 II.2
  h5 Développement
  p
    | Pour vous permettre d’aller plus loin dans le développement de votre site, nous vous
    | proposons une liste de fonctionnalités. Pour que les points soient pris en compte, vous
    | devez avoir correctement effectué l’installation et la configuration de votre serveur, votre
    | framework et votre base de données.
  p
    | Voici la liste des éléments que vous devez mettre en place :
  p
    | • Une page d’accueil.
  p
    | • Une section login / logout / création de compte.
  p
    | • Un panel admin avec gestion des utilisateurs, des groupes, etc... (indice : CRUD).
  p
    | • De l’URL rewriting.
  p
    | • Une gestion des permissions correcte.
  p
    | • De l’encryption (aucun mot de passe en clair).
  p
    | • De l’HTTPS.
  p
    | • Formulaire de contact ou newsletter (envoi d’ e-mail).
  p
    | • De la validation de données (data validation).

  br
  br

  h2 Chapitre III
  h3 Rendu

  p
    | • Vous devez rendre à la racine de votre dépôt le dossier complet de votre framework.
  p
    | • Pour la correction, vous devez uniquement cloner le depot dans le dossier pointé
    | par le virtualhost de votre serveur web.
  p
    |• Seul le contenu présent dans votre dépot sera évalué en soutenance.
  p
    |• Tout fichier inutile au projet sera pénalisé.

  br
  br

  h2 Chapitre IV
  h3 Consignes
  p
    | Les consignes suivantes seront présentes dans le barème de soutenance. Soyez très
    | attentifs lors de l’application de ces dernières car elles seront sanctionnées par un 0 sans
    | appel.
  p
    | • Pour ce projet, vous avez le droit d’utiliser tout les langages que vous souhaitez.
  p
    | • Les templates HTML sont autorisés.
  p
    | • Ce projet ne sera corrigé que par des humains.
  p
    | • Vous devez gérer les erreurs de manière sensible (ex : pas d’injection SQL possible).
  p
    | • L’arborescence de votre projet est indispensable, vous devez suivre la logique de
    | votre framework.
  p
    | • Tout ce qui n’est pas explicitement autorisé est interdit.
  p
    | • Pour toute question, merci de passer par le forum.
  p
    | Bon courage à tous !

app/views/welcomes/framework1.html.slim
.container
  h1 Sujet Framework 1

  h2
    | Chapitre II
  h3
    | Sujet
  h4
    | II.1 Internationalisation
  br
  p = "Comme première feature, sur votre page d’accueil, vous devez pouvoir choisir la langue de votre site. Tout le site sera traduit dans la langue selectionnée. Pensez a utiliser la puissance de votre framework. Quand vous vous déconnectez de votre site, il doit enregistrer la langue choisie pour une prochaine connexion."

  br
  h4 II.2 forum

  p
    = "Vous devez implémenter un forum a l’image de celui qui est a présent sur l’(ancien) intra. Voici les principales règles a respecter."
    br
    br
    b = "** Catégories : "
    = "Vous devez pouvoir ajouter / modifier / supprimer des catégories."
    br
    br
    b = "** Sous-Catégories : "
    = "Même consigne que pour les catégories."
    br
    br
    b = "** Threads : "
    = "Les threads peuvent appartenir a une catégorie ou a une sous-catégorie. Vous devez pouvoir repondre dans un thread et commenter une réponse."

  br
  h4 II.3 tickets

  p
    = "Cette partie consiste a mettre en place un gestionnaire de tickets afin de résoudre les éventuels problèmes utilisateurs."
    br
    br
    b = "** Création de tickets : "
    = "Tous les utilisateurs peuvent créer un ticket."
    br
    br
    b = "** Spool de tickets : "
    = "Les tickets créés arrivent dans le spool, seuls les admins y ont accès. C’est ici que les admins peuvent répondre ou attribuer les tickets a un autre admin."
    br
    br
    b = "** état d’un ticket : "
    = "Le ticket peut être ouvert ou fermé. Une fois fermé, il peut être réouvert par celui qui l’a créé ou un admin."

  br
  br
  h2
    | Chapitre III
  h3
    | Rendu
  br
  p
    = "** Vous devez rendre à la racine de votre dépôt le dossier complet de votre framework."
  br
  p
    = "** Pour la correction, vous devez uniquement cloner le dépôt dans le dossier pointé par le virtualhost de votre serveur web."
  br
  p
    = "** Seul le contenu présent dans votre dépôt sera évalué en soutenance."
  br
  p
    = "** Tout fichier inutile au projet sera pénalisé."

  h2
    | Chapitre IV
  h3
    | Consignes

  br
  p  = "Les consignes suivantes seront présentes dans le barème de soutenance. Soyez très attentifs lors de l’application de ces dernières car elles seront sanctionnées par un 0 sans appel."

  p = "** Pour ce projet, vous avez le droit d’utiliser tous les langages que vous souhaitez."

  p = "** Les templates HTML sont autorisés."

  p = "** Ce projet ne sera corrigé que par des humains."

  p = "** Vous devez gérer les erreurs de manière sensible (ex : pas d’injection SQL possible)."

  p = "** L’arborescence de votre projet est indispensable, vous devez suivre la logique de votre framework."

  p = "** Tout ce qui n’est pas explicitement autorisé est interdit."

  p = "** Pour toute question, merci de passer par le forum."

  p = "Bon courage à tous !"

app/views/welcomes/framework2.html.slim
h1 Sujet Framework 2

app/views/welcomes/index.html.slim
h1 = t('welcomes.h1_title')

h3.text-center
  = link_to 'Framework 0', sujet_framework0_path
  | &nbsp;&nbsp;&nbsp;
  = link_to 'Framework 1', sujet_framework1_path
  | &nbsp;&nbsp;&nbsp;
  = link_to 'Framework 2', sujet_framework2_path
  | &nbsp;&nbsp;&nbsp;
  = link_to 'Framework 3', sujet_bigwebproject_path

/ .container
/ .panel.panel-default
/   .panel-heading
/     h3 Last 20 logs
  / table.table.table-striped.table-bordered
  /   - if @result.present?
  /     - @result.each do |f|
  /       tr
  /         td dn
  /         td = f.dn
  /       tr
  /         td alias
  /         td
  /           - f.alias.each do |ert|
  /             = ert
  /             br
  /       tr
  /         td gidnumber
  /         td = f.gidnumber
  /       tr
  /         td loginshell
  /         td = f.loginshell
  /       tr
  /         td sn
  /         td = f.sn
  /       tr
  /         td uid
  /         td = f.uid
  /       tr
  /         td uidnumber
  /         td = f.uidnumber
  /       tr
  /         td cn
  /         td = f.cn
  /       tr
  /         td givenname
  /         td = f.givenname
  /       tr
  /         td homedirectory
  /         td = f.homedirectory
  /       tr
  /         = @entry