config/routes.rb
Rails.application.routes.draw do

  scope '/:locale' do
    mount Forem::Engine, :at => '/forums'

    devise_for :users

    get 'students'                    => 'students#index'
    post 'students/filter'                   => 'students#filter', as: 'filter_student'

    get 'group/index'                       => 'group#index'
    get 'users_list'                        => 'uuser#index'
    get 'users_list/:id'                    => 'uuser#show'
    get 'users_list/:id/logas'              => 'uuser#become_user', as: "admin_logas_user"
    get 'users_list/change_locale/:locale'  => 'uuser#set_local', as: "change_locale_user"

    get 'welcomes'                          => 'welcomes#index'
    get 'sujet/framework0'                  => 'welcomes#framework0'
    get 'sujet/framework1'                  => 'welcomes#framework1'
    get 'sujet/framework2'                  => 'welcomes#framework2'
    get 'sujet/bigwebproject'               => 'welcomes#bigwebproject'

    get 'contact'                           => 'contact#index'
    get 'contact/new'                       => 'contact#new'
    post 'contact/create'                   => 'contact#create'
    get 'contact/:id'                       => 'contact#show'

    get 'log/index'

    resources :tickets do
      resources :comments
    end

    get '/user/tickets'                     => 'tickets#user_index'

    scope '/adm' do
      get '/ticket/:id'                     => 'tickets#show_admin', as: "adm_ticket_show"
      get '/ticket/:id/edit'                => 'tickets#edit_admin', as: "adm_ticket_edit"
      patch '/ticket/:id/edit'              => 'tickets#update_admin'
    end

  end

  ActiveAdmin.routes(self)
  root :to => 'welcomes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates_presence_of :title
  validates_presence_of :message
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
  def login
    if !self.user_id.blank?
      User.find(self.user_id).login
    else
      "No User Id"
    end
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessor :login
  attr_accessor :cn
  attr_accessor :uidnumber


end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true
  validates :message, presence: true

  ### User
  def self.user_ticket_open_all(userId)
    self.where(user_id: userId, open: true)
  end

  def self.user_ticket_close_all(userId)
    self.where(user_id: userId, open: false)
  end

  ### Admin
  def self.ticket_open_all
    self.where(open: true)
  end

  def self.ticket_close_all
    self.where(open: false)
  end

  def self.ticket_no_assign
    self.where(open: true, admin_assign_id: nil)
  end

  def self.ticket_assign_to_me(userId)
    self.where(admin_assign_id: userId, open: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => {email: false, login42: true}

  validates :login, presence: true, uniqueness: true

   attr_accessor :login42

  # hack for remember_token
  def authenticatable_token
    Digest::SHA1.hexdigest(email)[0,29]
  end

  # Front-end navbar administration button
  def admin?
    if self && self.admin
      true
    else
      false
    end
  end

  def current_admin
    self && self.admin == true
  end

  def current_admin_forum
    self && self.forem_admin == true
  end

  # Forem
  def forem_name
    self.login
  end

  # Forem email gravatar
  def forem_email
    self.email
  end

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_action :logg, only: [:show, :create, :index, :destroy]
  def index
    @contacts = Contact.all
  end

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path
    else
      @contact_error = "Create Failed"
    end
  end

  def show
  end

  def contact_params
    params.require(:contact).permit(:firstname, :lastname, :entity, :phone, :email, :title, :message)
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!
  before_action :logg, only: [:index]

  def index
    @groups = Group.all
  end
end

app/controllers/log_controller.rb
class LogController < ApplicationController
  before_action :authenticate_user!
  before_action :logg, only: [:index, :destroy]

  def index
    @logs = Log.all.limit(20).order('created_at DESC')
  end

  def destroy
  end
end

app/controllers/page_controller.rb
class PagesController < ApplicationController
  #before_action :authenticate_user!
  before_action :logg, only: [:index]


  def index
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy, :show, :edit, :update, :new, :user_index]

  before_action :authenticate_admin!, only: [:index, :show_admin, :edit_admin, :update_admin]

  before_action :logg, only: [ :user_index, :show, :create, :update, :index, :show_admin, :update_admin, :destroy]

  ### User section
  def user_index
    @tickets = Ticket.where(user_id: current_user.id)
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def new
  end

  def create
    @ticket = Ticket.new(params_create_by_user)

    if @ticket.save
      redirect_to main_app.user_tickets_path
    else
      render 'new'
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])

    if @ticket.update(params_update_by_user)
      redirect_to "/" + I18n.locale.to_s + "/tickets/" + @ticket.id.to_s
    else
      render 'edit'
    end
  end

  ### Admin section
  def index
    @tickets = Ticket.all
  end

  def show_admin
    @ticket = Ticket.find(params[:id])
  end

  def edit_admin
    @ticket = Ticket.find(params[:id])
    @admins = User.where(admin: true)
  end

  def update_admin
    @ticket = Ticket.find(params[:id])

    if @ticket.update(params_update_by_admin)
      @adminAssign = User.find(@ticket.admin_assign_id)
      @ticket.admin_assign_login = @adminAssign.login
      @ticket.save
      redirect_to "/" + I18n.locale.to_s + "/adm/ticket/" + @ticket.id.to_s
    else
      render 'edit_admin'
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])

    if authenticate_admin!
      @ticket.destroy
      @path = tickets_path
    elsif current_user && current_user.id == @ticket.user_id
      @ticket.destroy
      @path = user_tickets_path
    else
      @path = root_path
    end

    redirect_to @path
  end

### Params Permits
  private
    def params_create_by_user
      params.require(:ticket).permit(:title, :message).merge(user_id: current_user.id, user_login: current_user.login)
    end

  private
    def params_update_by_user
      params.require(:ticket).permit(:title, :message, :open)
    end

  private
    def params_update_by_admin
      params.require(:ticket).permit(:title, :message, :admin_assign_id, :admin_assign_login, :open)
    end
end

app/controllers/uuser_controller.rb
class UuserController < ApplicationController
  before_action :authenticate_admin!

  before_action :logg, only: [:index, :show]

  def index
    @users = User.all
  end

  def show
  end

  def become_user
    return unless authenticate_admin!
    sign_in(:user, User.find(params[:id]), { :bypass => true })
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def resource_name
    :ticket
  end

  def resource_class
    Ticket
  end

  def resource
    @ticket ||= Ticket.new
  end

  def comment_resource_name
    :comment
  end

  def comment_resource_class
    Comment
  end

  def comment_resource
    @comment ||= Comment.new
  end

end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/contact/index.html.slim
h1 Contact

- @contacts.each do |f|
  = f.title
  br
  = f.email
  br
  = f.message
  hr

app/views/contact/new.html.slim
.container
  h1 = t('simple_form.contact.h1_title')

  - if @contact_error && !@contact_error.blank?
    .alert.alert-info
      = @contact_error

  = simple_form_for(:contact, url: contact_create_path, action: 'post') do |f|
    = f.input :firstname, as: :string, label: t('simple_form.contact.firstname'), :required => false
    = f.input :lastname, as: :string, label: t('simple_form.contact.lastname'), :required => false
    = f.input :entity, as: :string, label: t('simple_form.contact.entity'), :required => false
    = f.input :phone, as: :string, label: t('simple_form.contact.phone'), :required => false
    = f.input :email, as: :email, label: t('simple_form.contact.email'), :required => true
    = f.input :title, as: :string, label: t('simple_form.contact.title'), :required => true
    = f.input :message, as: :text, label: t('simple_form.contact.message'), :required => true
    = f.submit t('simple_form.contact.send')

app/views/group/index.html.slim
h1 = t('h1_title')

div
  table.table-striped
    tr
      td
        h3 Name
    - @groups.each do |f|
      tr
        td = f.name

app/views/log/index.html.slim
.container
  h1 Logs index
  br

.panel.panel-default
  .panel-heading
    h3 Last 20 logs
  table.table.table-striped.table-bordered
    tr
      th UserId
      th Controller
      th Action
      th URL
      th Created on
    - @logs.each do |l|
      tr
        td = l.login
        td = l.controller
        td = l.action
        td = l.url
        td = l.created_at

app/views/tickets/_admin_table_header.html.slim
tr
  th = t('ticket.posted_by')
  th = t('ticket.title')
  th = t('ticket.message')
  th = t('ticket.open?')
  th = t('ticket.assigned_to')
  th = t('ticket.action')

app/views/tickets/_admin_table_line.html.slim
tr
  td
    = ticket.user_login.truncate(10)
    = " (" + ticket.user_id.to_s + ")"
  td = ticket.title.truncate(32)
  td = ticket.message.truncate(22)
  td = ticket.open
  td
    = ticket.admin_assign_login
    = " (" + ticket.admin_assign_id.to_s + ")"
  td
    = link_to t('ticket.edit'), ("/" + I18n.locale.to_s + "/adm/ticket/" + ticket.id.to_s + "/edit")
    | &nbsp;&nbsp;
    = link_to t('ticket.show'), ("/" + I18n.locale.to_s + "/adm/ticket/" + ticket.id.to_s)
    /| &nbsp;&nbsp;
    /= link_to t('ticket.delete'), ("/" + I18n.locale.to_s + "/tickets/" + ticket.id.to_s), method: :delete, data: { confirm: 'Are your sure ?'}

app/views/tickets/_user_table_header.html.slim
tr
  th = t('ticket.open?')
  th = t('ticket.title')
  th = t('ticket.message')
  th = t('ticket.assigned_to')
  th = t('ticket.action')

app/views/tickets/_user_table_line.html.slim
tr
  td
    = ticket.open
  td
    = ticket.title
  td
    = ticket.message
  td
    = ticket.admin_assign_id
    | &nbsp;&nbsp;
    = ticket.admin_assign_login
  td
    = link_to t('ticket.edit'), ("/" + I18n.locale.to_s + "/tickets/" + ticket.id.to_s + "/edit")
    | &nbsp;&nbsp;
    = link_to t('ticket.Montrer'), ("/" + I18n.locale.to_s + "/tickets/" + ticket.id.to_s)
    /| &nbsp;&nbsp;
    /= link_to t('ticket.delete'), ("/" + I18n.locale.to_s + "/tickets/" + ticket.id.to_s), method: :delete, data: { confirm: t('ticket.are_your_sure?')}

app/views/tickets/edit.html.slim
br
.container
  = simple_form_for(resource, :as => resource_name, :url => ticket_path, method: :patch) do |f|
    .panel.panel-primary
      .panel-heading
        h2 = t('ticket.edit_ticket_user')
      .panel-body
        - if @ticket.errors.any?
          .alert.alert-danger
            h4
              = pluralize(@ticket.errors.count, "error")
              | &nbsp;&nbsp;prohibited this ticket from being saved:
              ul
                - @ticket.errors.full_messages.each do |msg|
                  li = msg

        br
        br
        .row
          .col-sm-3
            .panel.panel-default
                .panel-heading
                  h4 = t('ticket.open?')
                .panel-body
                  = @ticket.open
          .col-sm-3
            = f.input :open, :label => "Status:", :collection => [true, false], :include_blank => false
        br
        = f.input :title, :label => t('ticket.title')
        br
        = f.input :message, :label => t('ticket.message')
        br
        = f.submit t('ticket.send')

app/views/tickets/edit_admin.html.slim
br
.container
  = simple_form_for(resource, :as => resource_name, :url => adm_ticket_edit_path, method: :patch) do |f|
    .panel.panel-primary
      .panel-heading
        h2 = t('ticket.edit_ticket_admin')
      .panel-body
        - if @ticket.errors.any?
          .alert.alert-danger
            h4
              = pluralize(@ticket.errors.count, "error")
              | &nbsp;&nbsp;prohibited this ticket from being saved:
              ul
                - @ticket.errors.full_messages.each do |msg|
                  li = msg

        br
        br
        .row
          .col-sm-3
            .panel.panel-default
              .panel-heading
                h4 = t('ticket.assigned_to')
              .panel-body
                = @ticket.admin_assign_login
          .col-sm-3
            = f.input :admin_assign_id, :label => "Assignation d'admin", :collection => @admins, :label_method => :login, :value_method => :id, :include_blank => false

        br
        br
        .row
          .col-sm-3
            .panel.panel-default
              .panel-heading
                h4 = t('ticket.open?')
              .panel-body
                = @ticket.open
          .col-sm-3
            = f.input :open, :label => "Status:", :collection => [true, false], :include_blank => false
        br
        = f.input :title, :label => t('ticket.title')
        br
        = f.input :message, :label => t('ticket.message')
        br
        = f.submit t('ticket.send')

app/views/tickets/index.html.slim
br
.panel.panel-default
  .panel-heading
    h2 = t('ticket.list_no_assign')
  table.table.table-striped.table-bordered
    tr
      = render 'admin_table_header'
    - @tickets.ticket_no_assign.each do |ticket|
      = render 'admin_table_line', {:ticket => ticket}

.panel.panel-default
  .panel-heading
    h2 = t('ticket.list_to_manage')
  table.table.table-striped.table-bordered
    tr
      = render 'admin_table_header'
    - @tickets.ticket_assign_to_me(current_user.id).each do |ticket|
      = render 'admin_table_line', {:ticket => ticket}

.panel.panel-default
  .panel-heading
    h2 = t('ticket.list_opened_full')
  table.table.table-striped.table-bordered
    tr
      = render 'admin_table_header'
    - @tickets.ticket_open_all.each do |ticket|
      = render 'admin_table_line', {:ticket => ticket}

.panel.panel-default
  .panel-heading
    h3 = t('ticket.list_close_full')
  table.table.table-striped.table-bordered
    tr
      = render 'admin_table_header'
    - @tickets.ticket_close_all.each do |ticket|
      = render 'admin_table_line', {:ticket => ticket}

app/views/tickets/new.html.slim
h1 New Ticket

div
  = simple_form_for(resource, :as => resource_name, :url => tickets_path) do |f|
    - if @ticket.errors.any?
      .alert.alert-danger
        h4
          = pluralize(@ticket.errors.count, "error")
          | &nbsp;&nbsp;prohibited this ticket from being saved:
          ul
            - @ticket.errors.full_messages.each do |msg|
              li = msg

    = f.input :title, :label => t('ticket.title'), :placeholder => t('ticket.title')
    = f.input :message, :label => t('ticket.message'), :plaholder => t('ticket.message')
    = f.submit t('ticket.send')

app/views/tickets/show.html.slim
.container
  br
  .panel.panel-primary
    .panel-heading
      h2
        = "Ticket: "
        = @ticket.id
    .panel-body
      ul.nav.nav-tabs
        li
          = link_to t('ticket.edit'), ("/" + I18n.locale.to_s + "/tickets/" + @ticket.id.to_s + "/edit")
        li
          = link_to t('ticket.Montrer'), ("/" + I18n.locale.to_s + "/tickets/" + @ticket.id.to_s)
        li
          = link_to t('ticket.delete'), ("/" + I18n.locale.to_s + "/tickets/" + @ticket.id.to_s), method: :delete, data: { confirm: t('ticket.are_your_sure?')}
      br
      .container.row
        .col-sm-3
          .panel.panel-default
            .panel-heading
              h4 = t('ticket.open?')
            .panel-body
              = @ticket.open
        .col-sm-3
          .panel.panel-default
            .panel-heading
              h4 = t('ticket.assigned_to')
            .panel-body
              - if @ticket.admin_assign_id == nil || @ticket.admin_assign_login.blank?
                = t('ticket.list_no_assign_one')
              - else
                = @ticket.admin_assign_login
                = " (" + @ticket.admin_assign_id.to_s + ")"

      .panel.panel-default
        .panel-heading
          h4 = t('ticket.title')
        .panel-body
          = @ticket.title

      .panel.panel-default
        .panel-heading
          h4 = t('ticket.message')
        .panel-body
          = @ticket.message

.container
  -if @ticket.comments.count > 0
    br
      h3 = t('ticket.replies')
      br
      - @ticket.comments.each do |comment|
        .panel.panel-default
          .panel-heading
            h4 = comment.login
          .panel-body
            = comment.body

.container
  br
  br
  h3 = t('ticket.reply')
  = simple_form_for(comment_resource, :as => comment_resource_name, :url => ("/" + I18n.locale.to_s + "/tickets/" + @ticket.id.to_s + "/comments")) do |f|
    - if @ticket.errors.any?
      .alert.alert-danger
        h4
          = pluralize(@ticket.errors.count, "error")
          = t('ticket.prohibited_this_ticket_from_being_saved')
          ul
            - @ticket.errors.full_messages.each do |msg|
              li = msg
    = f.input :body, :label => false, :placeholder => t('ticket.message')
    = f.submit t('ticket.send')

app/views/tickets/show_admin.html.slim
.container
  br
  .panel.panel-primary
    .panel-heading
      h2
        = "Ticket: "
        = @ticket.id
    .panel-body
      ul.nav.nav-tabs
        li
          = link_to t('ticket.edit'), ("/" + I18n.locale.to_s + "/adm/ticket/" + @ticket.id.to_s + "/edit")
        li
          = link_to t('ticket.Montrer'), ("/" + I18n.locale.to_s + "/adm/ticket/" + @ticket.id.to_s)
        li
          = link_to t('ticket.delete'), ("/" + I18n.locale.to_s + "/tickets/" + @ticket.id.to_s), method: :delete, data: { confirm: t('ticket.are_your_sure?')}

      br
      .container.row
        .col-sm-3
          .panel.panel-default
            .panel-heading
              h4 = t('ticket.open?')
            .panel-body
              = @ticket.open
        .col-sm-3
          .panel.panel-default
            .panel-heading
              h4 = t('ticket.assigned_to')
            .panel-body
              - if @ticket.admin_assign_id == nil || @ticket.admin_assign_login.blank?
                = t('ticket.list_no_assign_one')
              - else
                = @ticket.admin_assign_login
                = " (" + @ticket.admin_assign_id.to_s + ")"

      .panel.panel-default
        .panel-heading
          h4 = t('ticket.title')
        .panel-body
          = @ticket.title

      .panel.panel-default
        .panel-heading
          h4 = t('ticket.message')
        .panel-body
          = @ticket.message

.container
  -if @ticket.comments.count > 0
    br
      h3 = t('ticket.replies')
      br
      - @ticket.comments.each do |comment|
        .panel.panel-default
          .panel-heading
            h4 = comment.login
          .panel-body
            = comment.body

.container
  br
  br
  h3 = t('ticket.reply')
  = simple_form_for(comment_resource, :as => comment_resource_name, :url => ("/" + I18n.locale.to_s + "/tickets/" + @ticket.id.to_s + "/comments")) do |f|
    - if @ticket.errors.any?
      .alert.alert-danger
        h4
          = pluralize(@ticket.errors.count, "error")
          = t('ticket.prohibited_this_ticket_from_being_saved')
          ul
            - @ticket.errors.full_messages.each do |msg|
              li = msg
    = f.input :body, :label => false, :placeholder => t('ticket.message')
    = f.submit t('ticket.send')

app/views/tickets/user_index.html.slim
.container
  h1 = t('ticket.all_my_tickets')
  h3 = link_to t('ticket.create_new_ticket'), main_app.new_ticket_path

.panel.panel-default
  .panel-heading
    h4 = t('ticket.list_opened_full')
  table.table.table-striped.table-bordered
    = render 'user_table_header'
    - @tickets.user_ticket_open_all(current_user.id).each do |ticket|
      = render 'user_table_line', {:ticket => ticket}
hr

.panel.panel-default
  .panel-heading
    h4 = t('ticket.list_close_full')
  table.table.table-striped.table-bordered
    = render 'user_table_header'
    - @tickets.user_ticket_close_all(current_user.id).each do |ticket|
      = render 'user_table_line', {:ticket => ticket}
hr